name: Monthly Rohlik sync

on:
  schedule:
    # Spustí se každý měsíc 2. den v 06:00 UTC (08:00 Praha)
    - cron: "0 6 2 * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run sync (headless)
        env:
          ROHLIK_ID: ${{ secrets.ROHLIK_ID }}
          ROHLIK_PIN: ${{ secrets.ROHLIK_PIN }}
        run: |
          python rohlik_sync.py --headless

      - name: Upload artifacts (debug)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: rohlik-debug
          path: ~/Desktop/rohlik_output