name: Monthly Rohlik sync

on:
  schedule:
    - cron: "0 6 2 * *"   # běží 2. den každého měsíce v 06:00 ráno
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium google-api-python-client google-auth google-auth-oauthlib webdriver-manager

      - name: Run Rohlik sync
        env:
          ROHLIK_ID: ${{ secrets.ROHLIK_ID }}
          ROHLIK_PIN: ${{ secrets.ROHLIK_PIN }}
        run: python rohlik_blocks_grid.py --headless