name: Monthly Rohlik sync

on:
  schedule:
    - cron: "15 1 1 * *"   # 1. den v měsíci 01:15 UTC
  workflow_dispatch: {}     # umožní ruční spuštění v Actions

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      TZ: Europe/Prague
      ROHLIK_ID: ${{ secrets.ROHLIK_ID }}
      ROHLIK_PIN: ${{ secrets.ROHLIK_PIN }}
      GCAL_CALENDAR_NAME: ${{ secrets.GCAL_CALENDAR_NAME }}
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      GOOGLE_TOKEN_JSON: ${{ secrets.GOOGLE_TOKEN_JSON }}

    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore Google credentials from secrets
        run: |
          echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json
          echo "$GOOGLE_TOKEN_JSON" > token.json

      - name: Run sync (headless)
        run: |
          python rohlik_blocks_grid.py --headless --calendar-name "$GCAL_CALENDAR_NAME"

      - name: Upload artifacts (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rohlik_output
          path: rohlik_output
