name: Monthly Rohlik sync

on:
  workflow_dispatch:
  schedule:
    # 2. den v měsíci v 04:15 UTC (≈ 05:15/06:15 podle času v ČR)
    - cron: '15 4 2 * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Restore Google credentials from secrets
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          GOOGLE_TOKEN_JSON: ${{ secrets.GOOGLE_TOKEN_JSON }}
        run: |
          echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json
          echo "$GOOGLE_TOKEN_JSON" > token.json

      - name: Run sync (headless)
        env:
          ROHLIK_ID: ${{ secrets.ROHLIK_ID }}
          ROHLIK_PIN: ${{ secrets.ROHLIK_PIN }}
          GCAL_CALENDAR_NAME: ${{ secrets.GCAL_CALENDAR_NAME }}
        run: |
          python rohlik_sync.py --headless --calendar-name "${GCAL_CALENDAR_NAME:-Rohlik směny}"

      - name: Upload artifacts (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: |
            grid.html
            grid.png
            candidates.txt
          if-no-files-found: ignore
