name: Monthly Rohlik sync

on:
  workflow_dispatch:
  schedule:
    # Běží 2. den v měsíci v 06:10 UTC (GitHub cron je vždy UTC).
    # Pokud chceš pevně 06:10 v Praze, počítej s posunem vůči UTC (zimní/letní čas).
    - cron: "10 6 2 * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          else
            python -m pip install --upgrade pip
            pip install selenium webdriver-manager
          fi

      - name: Run sync (headless)
        env:
          ROHLIK_ID: ${{ secrets.ROHLIK_ID }}
          ROHLIK_PIN: ${{ secrets.ROHLIK_PIN }}
        shell: bash
        run: |
          set -e
          echo "Working dir:"; pwd; ls -la
          # Nejprve headless, když skript parametr nezná, zkusí se bez něj
          python3 rohlik_to_ics_panel.py --headless || python3 rohlik_to_ics_panel.py

      - name: Upload artifacts (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rohlik-artifacts
          path: |
            **/*.ics
            **/grid.html
            **/grid.png
            **/candidates.txt
          if-no-files-found: warn
