name: Monthly Rohlik sync

on:
  schedule:
    # každý měsíc druhého dne ve 4 ráno
    - cron: "0 4 2 * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Restore Google credentials from secrets
        run: |
          echo "${{ secrets.GCAL_CREDENTIALS }}" > credentials.json
          echo "${{ secrets.GCAL_TOKEN }}" > token.json

      - name: Run sync (headless)
        run: python rohlik_sync.py --calendar-name "Rohlik směny" --headless

      - name: Upload artifacts (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rohlik_output
          path: ~/Desktop/rohlik_output
          if-no-files-found: ignore