name: Monthly Rohlik sync

on:
  workflow_dispatch:
  schedule:
    # 2. den v měsíci v 06:10 UTC (GitHub cron je vždy v UTC).
    - cron: "10 6 2 * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install selenium webdriver-manager google-api-python-client google-auth google-auth-oauthlib
          fi

      # Volitelné: pokud skript zapisuje do Google Kalendáře a máš tyto secrety,
      # uloží se sem credentials.json a token.json
      - name: Restore Google credentials from secrets
        if: ${{ secrets.GOOGLE_CREDENTIALS_JSON != '' }}
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.json
          echo "${{ secrets.GOOGLE_TOKEN_JSON }}" > token.json

      - name: Run sync (headless)
        env:
          ROHLIK_ID: ${{ secrets.ROHLIK_ID }}
          ROHLIK_PIN: ${{ secrets.ROHLIK_PIN }}
        shell: bash
        run: |
          set -e
          echo "pwd: $(pwd)"
          ls -la
          # Nejprve se zkusí headless; pokud skript parametr nezná, spustí se bez něj
          python3 rohlik_blocks_grid.py --headless || python3 rohlik_blocks_grid.py

      - name: Upload artifacts (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rohlik-artifacts
          path: |
            **/*.ics
            **/grid.html
            **/grid.png
            **/candidates.txt
          if-no-files-found: warn
