name: Monthly Rohlik sync

on:
  workflow_dispatch: {}               # ruční spuštění z GitHubu
  schedule:
    - cron: "15 4 2 * *"              # každý měsíc 2. den v 04:15 UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    # Propojení na secrets/vars (nic dalšího nemusíš měnit)
    env:
      ROHLIK_ID: ${{ secrets.ROHLIK_ID }}
      ROHLIK_PIN: ${{ secrets.ROHLIK_PIN }}
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      GOOGLE_TOKEN_JSON: ${{ secrets.GOOGLE_TOKEN_JSON }}
      GCAL_CALENDAR_NAME: ${{ secrets.GCAL_CALENDAR_NAME }}  # nech prázdné = použije se default

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install selenium webdriver-manager google-api-python-client google-auth google-auth-oauthlib
          fi

      - name: Restore Google credentials from secrets
        run: |
          # zapíše credentials.json / token.json do pracovního adresáře
          if [ -n "${GOOGLE_CREDENTIALS_JSON}" ]; then printf '%s' "${GOOGLE_CREDENTIALS_JSON}" > credentials.json; fi
          if [ -n "${GOOGLE_TOKEN_JSON}" ];  then printf '%s' "${GOOGLE_TOKEN_JSON}"  > token.json;        fi

      - name: Run sync (headless)
        run: |
          # default kalendář, když není GCAL_CALENDAR_NAME vyplněné v secrets
          CAL_NAME="${GCAL_CALENDAR_NAME:-Rohlik směny}"
          python rohlik_sync.py --calendar-name "${CAL_NAME}" --headless

      - name: Upload artifacts (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rohlik-output
          path: |
            $HOME/Desktop/rohlik_output/**
          if-no-files-found: ignore
          retention-days: 7